"""Golden fixtures for the JOSM plugin's Kotlin tiler.

The plugin reimplements ``infer.predict``'s windowing in Kotlin, and a second
implementation of anything is where train/serve skew lives. This project has
already lost fourteen builds to a silent raster misregistration that no test
was watching for, so the Kotlin side is checked against values produced by *this*
code rather than against its own idea of what the answer should be.

Generated by ``trailer golden``, and by the plugin's Maven build via
exec-maven-plugin so the fixtures cannot drift from the Python unnoticed. The
output is committed as well, so the plugin still builds on a machine with no
Python toolchain (``-Dgolden.skip=true``).
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

import numpy as np

log = logging.getLogger(__name__)

DEFAULT_OUT = Path("plugin/src/test/resources/golden.json")

#: Tiling cases as ``(n, tile, step, stride)``, chosen to cover the branches
#: that actually differ: a raster shorter than one window (the only case still
#: padded), an exact fit, a ragged tail whose flush origin is not a multiple of
#: the step, and stride 2, where that origin is quantised down and so is *not*
#: simply ``n - tile``.
PAD_CASES = ((100, 64, 32, 1), (64, 64, 32, 1), (50, 64, 32, 1),
             (129, 64, 32, 1), (1121, 256, 128, 1), (200, 128, 64, 1),
             (65, 64, 32, 1), (1121, 512, 256, 2), (2242, 512, 152, 2),
             (300, 128, 64, 2))

#: Whole-tile parity cases: (variant, body tile, raster height, raster width).
#:
#: Both rasters are ragged on both axes, so the flush final window -- the one
#: that is *not* a multiple of the step -- is inside the compared region rather
#: than off the end of it. That is the window the old padded rule got wrong, and
#: an exact-fit raster would exercise neither rule. ``dem1`` is the case that
#: ships. ``lidar05`` is stride 2, where a window origin has to be divided down
#: to the body grid -- the arithmetic that a Kotlin-only test would have had no
#: way to check, and the exact shape of the step bug this project already found
#: once. No stride-2 variant is deployable (they all need canopy bands, which no
#: elevation service provides), so without this case that division would ship
#: never having been run against Python at all.
TILE_CASES = (("dem1", 32, 70, 54), ("lidar05", 32, 140, 108))


def _stub_conv(stride: int):
    """A fixed 3x3 convolution standing in for the trained network.

    Deliberately asymmetric in both axes, so a window that lands one pixel off,
    or transposed, cannot agree by symmetry. It has a receptive field on purpose
    too: a 1x1 kernel would make each output depend only on the co-located input
    and a misregistration would show only as a shift, which is much easier to
    accidentally reproduce on both sides than a wrong *value*.
    """
    import torch

    conv = torch.nn.Conv2d(1, 1, 3, stride=stride, padding=1, bias=True)
    conv.weight.data = torch.tensor(
        [[-0.70, 0.15, 0.40],
         [0.05, 1.30, -0.25],
         [0.60, -0.90, 0.20]]).reshape(1, 1, 3, 3)
    conv.bias.data = torch.tensor([-0.35])
    return conv


def _stub_net(stride: int):
    """What ``infer.predict`` sees: called as ``model(z, canopy, variant=...)``,
    returning *logits*, because ``predict`` applies the sigmoid itself."""
    import torch

    class StubNet(torch.nn.Module):
        def __init__(self):
            super().__init__()
            self.conv = _stub_conv(stride)

        def forward(self, z, canopy=None, variant=None):
            # Canopy is accepted and ignored. The 0.5 m variants need it to
            # exist so `predict` will run them, but nothing deployable has it,
            # and this case is here for the stride arithmetic rather than the
            # bands.
            return self.conv(z)

    return StubNet()


def _stub_deployable(net):
    """What the plugin sees: the same weights behind the exported contract.

    Mirrors ``model.Deployable`` -- sigmoid applied inside, taper as a second
    output -- so the ONNX the plugin runs and the module ``infer.predict`` runs
    are the same arithmetic reached two different ways. That is the whole point:
    if the export or the Kotlin tiling disagrees, these two stop matching.
    """
    import torch

    from . import infer

    class StubDeployable(torch.nn.Module):
        def __init__(self):
            super().__init__()
            self.net = net

        def forward(self, z):
            p = torch.sigmoid(self.net(z))
            taper = infer.hann2d(p.shape[-1], p.device, p.dtype)
            return p, taper.expand_as(p)

    return StubDeployable()


def _terrain(h: int, w: int, seed: int):
    """Deterministic pseudo-elevation: a tilted plane plus noise.

    Tilted so the raster is asymmetric under both flips and the transpose, and
    in metres rather than normalised, because that is what the real input is.
    """
    rng = np.random.default_rng(seed)
    ramp = (np.linspace(0.0, 40.0, h)[:, None]
            + np.linspace(0.0, 25.0, w)[None, :])
    return (ramp + rng.standard_normal((h, w)) * 3.0).astype("float32")


def _tile_case(variant: str, body: int, h: int, w: int, out_dir: Path,
               overlap: float = 0.5) -> dict:
    import torch

    from . import infer
    from . import model as model_mod
    from . import variants as var_mod

    v = var_mod.get(variant)
    tile = body * v.stride
    net = _stub_net(v.stride).eval()

    z = _terrain(h, w, seed=20260808 + h)
    # Ignored by the stub, but `predict` refuses to run a canopy variant
    # without it. Zeros, because what this case is testing is the stride
    # division, not the bands.
    canopy = (np.zeros((2, h, w), dtype="float32") if v.canopy else None)

    with torch.no_grad():
        prob = infer.predict(net, z[None], canopy=canopy, variant=variant,
                             body_tile=body, overlap=overlap, device="cpu")

    onnx_name = f"stub-{variant}.onnx"
    with torch.no_grad():
        torch.onnx.export(
            _stub_deployable(net).eval(),
            (torch.zeros(1, 1, tile, tile),),
            str(out_dir / onnx_name),
            input_names=["elevation_m"],
            output_names=["trail_probability", "window_taper"],
            opset_version=17)

    # Shaped exactly like a real export sidecar, and the numbers come from the
    # same `window_step` and the same variant table, so ModelSpec validates it
    # the same way. The real sidecars are checked against a real export in
    # ModelSpecTest; this one only has to be a valid contract.
    sidecar = {
        "variant": variant, "res_m": v.res, "out_res_m": var_mod.BODY_RES,
        "input_px": tile, "output_px": body, "stride": v.stride,
        "overlap": overlap,
        "step_px": infer.window_step(tile, overlap, v.stride),
        "edge_windows": "flush", "pad_mode": "reflect", "tta": False,
        "outputs": ["trail_probability", "window_taper"],
        "license": model_mod.MODEL_LICENSE,
        "attribution": model_mod.MODEL_ATTRIBUTION,
    }
    (out_dir / f"stub-{variant}.json").write_text(json.dumps(sidecar, indent=1))

    return {
        "variant": variant, "onnx": onnx_name, "sidecar": f"stub-{variant}.json",
        "h": h, "w": w, "body_tile": body, "stride": v.stride,
        "z": z.flatten().tolist(),
        "out_h": h // v.stride, "out_w": w // v.stride,
        "out": prob[0].flatten().tolist(),
    }


def build(out_dir: Path = DEFAULT_OUT.parent) -> dict:
    import torch
    import torch.nn.functional as F

    from . import infer

    g: dict = {}

    size = 8
    g["hann_size"] = size
    g["hann"] = infer.hann2d(size, "cpu").flatten().tolist()

    g["pad_cases"] = []
    for n, tile, step, stride in PAD_CASES:
        pad = infer._pad_to(n, tile, step)
        g["pad_cases"].append({
            "n": n, "tile": tile, "step": step, "stride": stride, "pad": pad,
            "origins": infer.window_origins(n + pad, tile, step, stride),
        })

    # Bottom/right reflect padding on a deliberately asymmetric ramp -- a
    # symmetric source would hide an off-by-one in the reflection index.
    h, w, ph, pw = 5, 4, 2, 3
    src = (np.arange(h * w, dtype="float32").reshape(h, w) * 0.5 - 3.0)
    padded = F.pad(torch.from_numpy(src)[None, None], (0, pw, 0, ph),
                   mode="reflect")[0, 0]
    g["reflect"] = {"h": h, "w": w, "pad_h": ph, "pad_w": pw,
                    "src": src.flatten().tolist(),
                    "out": padded.numpy().flatten().tolist()}

    H, W, tile, step = 20, 20, 8, 4
    taper = infer.hann2d(tile, "cpu").numpy()
    acc = np.zeros((H, W), dtype="float64")
    den = np.zeros((H, W), dtype="float64")
    wins = [(r, c) for r in infer.window_origins(H, tile, step, 1)
            for c in infer.window_origins(W, tile, step, 1)]
    probs = []
    rr, cc = np.meshgrid(np.arange(tile), np.arange(tile), indexing="ij")
    for i, (r, c) in enumerate(wins):
        # Distinct per window and asymmetric in both axes, so a transposed or
        # window-order bug cannot coincidentally agree.
        p = ((0.05 * i + 0.01 * rr + 0.003 * cc) % 1.0).astype("float32")
        probs.append(p)
        acc[r:r + tile, c:c + tile] += p * taper
        den[r:r + tile, c:c + tile] += taper
    g["blend"] = {"h": H, "w": W, "tile": tile, "step": step,
                  "windows": [{"row": r, "col": c} for r, c in wins],
                  "probs": [p.flatten().tolist() for p in probs],
                  "out": (acc / np.maximum(den, 1e-6)).flatten().tolist()}

    # Whole-tile parity: the one fixture that runs the *entire* path rather
    # than a piece of it. Everything above tests one function against Python;
    # this runs a real onnxruntime session under the Kotlin tiler and compares
    # the finished raster to what `infer.predict` produced from the same
    # weights. It is the only fixture that would catch the two sides each being
    # individually correct and still disagreeing when composed.
    out_dir.mkdir(parents=True, exist_ok=True)
    g["tiles"] = [_tile_case(variant, body, h, w, out_dir)
                  for variant, body, h, w in TILE_CASES]
    return g


def real_parity(checkpoint: Path, tile_dir: Path, out_dir: Path,
                variant: str = "dem1", window: int = 256,
                max_px: int = 1024, overlap: float = 0.5,
                tta: bool = False) -> dict:
    """Full-scale parity fixture: the real model, on real elevation.

    The committed fixture in :func:`_tile_case` runs a 2.6 KB stand-in, which is
    the right trade for a test that must live in git -- it exercises the tiling
    and the session plumbing, and those are what the plugin reimplements.

    What it cannot exercise is the trained graph itself: a ResNet-34 encoder,
    the im2col median filter, and ~99 MB of initialisers, at a 256 px window
    rather than 32. Whether onnxruntime's *Java* runtime handles all of that is
    a different question from whether Python's does, and it is not one a stub
    can answer.

    So this writes the fixture somewhere outside the repository and the plugin
    has an opt-in test that points at it. Checked-in code, generated artefact,
    nothing 99 MB in git.
    """
    import numpy as np
    import torch

    from . import infer
    from . import model as model_mod
    from . import variants as var_mod
    from .data import full_tile

    out_dir.mkdir(parents=True, exist_ok=True)
    v = var_mod.get(variant)
    net, meta = model_mod.load(checkpoint)

    onnx = out_dir / "model.onnx"
    info = model_mod.export_onnx(net, variant, onnx, size=window,
                                 overlap=overlap, tta=tta)
    (out_dir / "model.json").write_text(json.dumps(info, indent=1))

    z, canopy, *_ = full_tile(tile_dir, v)
    # Bounded so the check stays minutes rather than hours; the corner is as
    # good as anywhere and keeps the ragged-edge padding in play.
    z = np.ascontiguousarray(z[:, :max_px, :max_px])
    _, h, w = z.shape

    with torch.no_grad():
        prob = infer.predict(net, z, canopy=None, variant=variant,
                             body_tile=window, overlap=overlap,
                             device="cpu", tta=tta)

    z.astype("<f4").tofile(out_dir / "z.f32")
    prob[0].astype("<f4").tofile(out_dir / "expected.f32")
    manifest = {
        "checkpoint": str(checkpoint), "tile": tile_dir.name,
        "variant": variant, "h": h, "w": w,
        "out_h": prob.shape[-2], "out_w": prob.shape[-1],
        "stride": v.stride, "window": window, "tta": tta,
        "mean_prob": round(float(prob.mean()), 6),
    }
    (out_dir / "parity.json").write_text(json.dumps(manifest, indent=1))
    log.info("wrote %s: %dx%d elevation, %dx%d probability, mean %.4f",
             out_dir, h, w, prob.shape[-2], prob.shape[-1], float(prob.mean()))
    return manifest


def write(out: Path = DEFAULT_OUT) -> Path:
    g = build(out.parent)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(g))
    log.info("wrote %s: hann %dx%d, %d pad cases, blend %dx%d over %d windows, "
             "%d whole-tile cases (%s)",
             out, g["hann_size"], g["hann_size"], len(g["pad_cases"]),
             g["blend"]["h"], g["blend"]["w"], len(g["blend"]["windows"]),
             len(g["tiles"]), ", ".join(t["variant"] for t in g["tiles"]))
    return out
