"""Golden fixtures for the JOSM plugin's Kotlin tiler.

The plugin reimplements ``infer.predict``'s windowing in Kotlin, and a second
implementation of anything is where train/serve skew lives. This project has
already lost fourteen builds to a silent raster misregistration that no test
was watching for, so the Kotlin side is checked against values produced by *this*
code rather than against its own idea of what the answer should be.

Generated by ``trailer golden``, and by the plugin's Maven build via
exec-maven-plugin so the fixtures cannot drift from the Python unnoticed. The
output is committed as well, so the plugin still builds on a machine with no
Python toolchain (``-Dgolden.skip=true``).
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

import numpy as np

log = logging.getLogger(__name__)

DEFAULT_OUT = Path("plugin/src/test/resources/golden.json")

#: Cases chosen to cover the branches that actually differ: a raster shorter
#: than one window, an exact fit, and a ragged tail needing Python's
#: negative-modulo behaviour (which Kotlin's `rem` does not reproduce).
PAD_CASES = ((100, 64, 32), (64, 64, 32), (50, 64, 32), (129, 64, 32),
             (1121, 256, 128), (200, 128, 64), (65, 64, 32))


def build() -> dict:
    import torch
    import torch.nn.functional as F

    from . import infer

    g: dict = {}

    size = 8
    g["hann_size"] = size
    g["hann"] = infer.hann2d(size, "cpu").flatten().tolist()

    g["pad_cases"] = []
    for n, tile, step in PAD_CASES:
        pad = infer._pad_to(n, tile, step)
        g["pad_cases"].append({
            "n": n, "tile": tile, "step": step, "pad": pad,
            "origins": list(range(0, (n + pad) - tile + 1, step)),
        })

    # Bottom/right reflect padding on a deliberately asymmetric ramp -- a
    # symmetric source would hide an off-by-one in the reflection index.
    h, w, ph, pw = 5, 4, 2, 3
    src = (np.arange(h * w, dtype="float32").reshape(h, w) * 0.5 - 3.0)
    padded = F.pad(torch.from_numpy(src)[None, None], (0, pw, 0, ph),
                   mode="reflect")[0, 0]
    g["reflect"] = {"h": h, "w": w, "pad_h": ph, "pad_w": pw,
                    "src": src.flatten().tolist(),
                    "out": padded.numpy().flatten().tolist()}

    H, W, tile, step = 20, 20, 8, 4
    taper = infer.hann2d(tile, "cpu").numpy()
    acc = np.zeros((H, W), dtype="float64")
    den = np.zeros((H, W), dtype="float64")
    wins = [(r, c) for r in range(0, H - tile + 1, step)
            for c in range(0, W - tile + 1, step)]
    probs = []
    rr, cc = np.meshgrid(np.arange(tile), np.arange(tile), indexing="ij")
    for i, (r, c) in enumerate(wins):
        # Distinct per window and asymmetric in both axes, so a transposed or
        # window-order bug cannot coincidentally agree.
        p = ((0.05 * i + 0.01 * rr + 0.003 * cc) % 1.0).astype("float32")
        probs.append(p)
        acc[r:r + tile, c:c + tile] += p * taper
        den[r:r + tile, c:c + tile] += taper
    g["blend"] = {"h": H, "w": W, "tile": tile, "step": step,
                  "windows": [{"row": r, "col": c} for r, c in wins],
                  "probs": [p.flatten().tolist() for p in probs],
                  "out": (acc / np.maximum(den, 1e-6)).flatten().tolist()}
    return g


def write(out: Path = DEFAULT_OUT) -> Path:
    g = build()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(g))
    log.info("wrote %s: hann %dx%d, %d pad cases, blend %dx%d over %d windows",
             out, g["hann_size"], g["hann_size"], len(g["pad_cases"]),
             g["blend"]["h"], g["blend"]["w"], len(g["blend"]["windows"]))
    return out
